name: Sync Bangumi Data

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 2:00 (北京时间 10:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create R18 filter script
        run: |
          cat > filter_r18.jq << 'EOF'
          map(select(
            (.nsfw != true) and
            (.tags // [] | map(.name // "") | 
              any(test("里番|18禁|18x|r18|成人|アダルト|エロ|h-game|eroge|adult|hentai|porn|xxx|sex"; "i")) | not
            ) and
            ((.name // "") + (.name_cn // "") | 
              test("里番|18禁|18x|r18|成人|アダルト|エロ|h-game|eroge|adult|hentai|porn|xxx|sex"; "i") | not
            )
          ))
          EOF

      - name: Create directories
        run: |
          mkdir -p public/data/bangumi
          mkdir -p tmp/bangumi

      - name: Sync Bangumi data
        env:
          BANGUMI_USER_ID: ${{ secrets.BANGUMI_USER_ID }}
          BANGUMI_TOKEN: ${{ secrets.BANGUMI_TOKEN }}
        run: |
          UPDATED=0
          
          # 定义所有类型和状态的组合
          declare -A TYPE_MAP=(
            ["book"]="1"
            ["anime"]="2" 
            ["music"]="3"
            ["game"]="4"
            ["real"]="6"
          )
          
          declare -A STATUS_MAP=(
            ["wish"]="1"
            ["collect"]="2"
            ["do"]="3"
            ["on_hold"]="4"
            ["dropped"]="5"
          )
          
          # 为每个类型创建目录
          for type_name in "${!TYPE_MAP[@]}"; do
            mkdir -p "tmp/bangumi/${type_name}"
            for status_name in "${!STATUS_MAP[@]}"; do
              mkdir -p "tmp/bangumi/${type_name}_${STATUS_MAP[$status_name]}"
            done
          done
          
          # 同步每个类型和状态的组合
          for type_name in "${!TYPE_MAP[@]}"; do
            type_id="${TYPE_MAP[$type_name]}"
            echo "Processing type: $type_name (API type: $type_id)"
            
            for status_name in "${!STATUS_MAP[@]}"; do
              status_id="${STATUS_MAP[$status_name]}"
              collection_key="${type_name}_${status_id}"
              
              echo "Syncing $collection_key..."
              
              # 获取远程数据总数
              remote_response=$(curl -s "https://api.bgm.tv/v0/users/${BANGUMI_USER_ID}/collections?subject_type=${type_id}&type=${status_id}&limit=1" \
                -H "Authorization: Bearer ${BANGUMI_TOKEN}" \
                -H "User-Agent: Fuwari-Bangumi-Sync/1.0")
              
              if [ $? -ne 0 ] || [ -z "$remote_response" ]; then
                echo "Failed to fetch data for $collection_key"
                continue
              fi
              
              remote_total=$(echo "$remote_response" | jq -r '.total // 0')
              
              # 检查本地文件
              local_file="public/data/bangumi/${collection_key}.json"
              if [ -f "$local_file" ]; then
                local_total=$(jq -r 'length' "$local_file")
              else
                local_total=0
                echo '[]' > "$local_file"
              fi
              
              echo "Processing $collection_key: remote_total=$remote_total, local_total=$local_total"
              
              # 如果数量不同，则更新
              if [ "$remote_total" -ne "$local_total" ] || [ "$remote_total" -gt 0 ]; then
                echo "Updating $collection_key..."
                
                # 创建临时文件
                temp_file="tmp/bangumi/${collection_key}/data.json"
                echo '[]' > "$temp_file"
                
                if [ "$remote_total" -gt 0 ]; then
                  # 分页获取所有数据
                  limit=50
                  offset=0
                  
                  while [ $offset -lt $remote_total ]; do
                    echo "Fetching $collection_key: offset=$offset, limit=$limit"
                    
                    page_data=$(curl -s "https://api.bgm.tv/v0/users/${BANGUMI_USER_ID}/collections?subject_type=${type_id}&type=${status_id}&limit=${limit}&offset=${offset}" \
                      -H "Authorization: Bearer ${BANGUMI_TOKEN}" \
                      -H "User-Agent: Fuwari-Bangumi-Sync/1.0")
                    
                    if [ $? -ne 0 ] || [ -z "$page_data" ]; then
                      echo "Failed to fetch page data for $collection_key at offset $offset"
                      break
                    fi
                    
                    # 提取数据并追加到临时文件
                    echo "$page_data" | jq -r '.data // []' > "tmp/bangumi/${collection_key}/page_${offset}.json"
                    
                    offset=$((offset + limit))
                    sleep 0.5  # 避免请求过于频繁
                  done
                  
                  # 合并所有页面数据
                  if ls tmp/bangumi/${collection_key}/page_*.json 1> /dev/null 2>&1; then
                    jq -s 'add' tmp/bangumi/${collection_key}/page_*.json > "$temp_file"
                  fi
                fi
                
                # 应用 R18 过滤
                if [ -f "$temp_file" ]; then
                  jq -f filter_r18.jq "$temp_file" > "${local_file}.tmp"
                  mv "${local_file}.tmp" "$local_file"
                  UPDATED=1
                  echo "Updated $collection_key with $(jq length "$local_file") items"
                else
                  echo "No data file found for $collection_key"
                fi
              else
                echo "$collection_key is up to date"
              fi
            done
          done
          
          # 生成汇总数据
          echo "Generating summary..."
          summary_file="public/data/bangumi/summary.json"
          
          # 创建汇总 JSON
          echo '{' > "$summary_file"
          first=true
          
          for type_name in "${!TYPE_MAP[@]}"; do
            for status_name in "${!STATUS_MAP[@]}"; do
              status_id="${STATUS_MAP[$status_name]}"
              collection_key="${type_name}_${status_id}"
              local_file="public/data/bangumi/${collection_key}.json"
              
              if [ "$first" = true ]; then
                first=false
              else
                echo ',' >> "$summary_file"
              fi
              
              if [ -f "$local_file" ]; then
                echo "  \"$collection_key\": $(cat "$local_file")" >> "$summary_file"
              else
                echo "  \"$collection_key\": []" >> "$summary_file"
              fi
            done
          done
          
          echo '}' >> "$summary_file"
          
          # 清理临时文件
          rm -rf tmp/bangumi
          rm -f filter_r18.jq
          
          echo "UPDATED=$UPDATED" >> $GITHUB_ENV

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [ "$UPDATED" -eq 1 ]; then
            git add public/data/bangumi/
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update Bangumi data - $(date +'%Y-%m-%d %H:%M:%S')"
              git push
              echo "Successfully updated Bangumi data"
            fi
          else
            echo "No updates needed"
          fi
